/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'alexander' at '12/13/16 2:50 PM' with Gradle 3.2.1
 *
 * @author alexander, @date 12/13/16 2:50 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
